%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-realsense2-camera
Version:        4.56.4
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS realsense2_camera package

License:        Apache License 2.0
URL:            http://www.ros.org/wiki/RealSense
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       ros-kilted-builtin-interfaces
Requires:       ros-kilted-cv-bridge
Requires:       ros-kilted-diagnostic-updater
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-image-transport
Requires:       ros-kilted-launch-ros
Requires:       ros-kilted-librealsense2
Requires:       ros-kilted-lifecycle-msgs
Requires:       ros-kilted-nav-msgs
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rclcpp-components
Requires:       ros-kilted-rclcpp-lifecycle
Requires:       ros-kilted-realsense2-camera-msgs
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-tf2
Requires:       ros-kilted-tf2-ros
Requires:       ros-kilted-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-builtin-interfaces
BuildRequires:  ros-kilted-cv-bridge
BuildRequires:  ros-kilted-diagnostic-updater
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-image-transport
BuildRequires:  ros-kilted-librealsense2
BuildRequires:  ros-kilted-lifecycle-msgs
BuildRequires:  ros-kilted-nav-msgs
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rclcpp-components
BuildRequires:  ros-kilted-rclcpp-lifecycle
BuildRequires:  ros-kilted-realsense2-camera-msgs
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-tf2
BuildRequires:  ros-kilted-tf2-ros
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-numpy
BuildRequires:  python%{python3_pkgversion}-requests
BuildRequires:  python3-tqdm
BuildRequires:  ros-kilted-ament-cmake-gtest
BuildRequires:  ros-kilted-ament-cmake-pytest
BuildRequires:  ros-kilted-launch-pytest
BuildRequires:  ros-kilted-launch-testing
BuildRequires:  ros-kilted-ros2topic
BuildRequires:  ros-kilted-sensor-msgs-py
BuildRequires:  ros-kilted-tf2-ros-py
%endif

%description
RealSense camera package allowing access to Intel D400 3D cameras

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Wed Jul 23 2025 LibRealSense ROS Team <librs.ros@intel.com> - 4.56.4-3
- Autogenerated by Bloom

* Tue Jul 22 2025 LibRealSense ROS Team <librs.ros@intel.com> - 4.56.4-2
- Autogenerated by Bloom

